name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-small-linux-image:${{ github.sha }}
    - name: Lint Markdown
      # You may pin to the exact commit or the version.
      # uses: tomwhross/write-good-action@4d9b6eeacd2a6e7c8d3ea0c3fd1643b5d033b2ea
      uses: tomwhross/write-good-action@v1.2
